# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '32be4b0e-237f-430d-9289-c5966a5c9829'
    definition: '3'
    buildVersionToDownload: 'latest'
    artifactName: 'passport-saml'
    itemPattern: '!*/node_modules/*'
    targetPath: '$(Pipeline.Workspace)/saml'
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '32be4b0e-237f-430d-9289-c5966a5c9829'
    definition: '4'
    buildVersionToDownload: 'latest'
    artifactName: 'passport-openidconnect'
    itemPattern: '!*/node_modules/*'
    targetPath: '$(Pipeline.Workspace)/openid'

- script: |
    ls -al 
    ls -al $(Pipeline.Workspace)
    ls -al $(Pipeline.Workspace)/saml
    npm install $(Pipeline.Workspace)/openid/lib
    npm install $(Pipeline.Workspace)/saml/lib/passport-saml
  displayName: 'checking the working directory and npm install'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'gluu-passport'
    publishLocation: 'pipeline'


